services:
  mysql:
    image: mysql:latest
    container_name: spring_rest_api_base
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_rest_api_base
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - spring_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      retries: 10
      start_period: 20s

  app:
    build: .
    container_name: spring_app
    depends_on:
      mysql:
        condition: service_healthy 
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTIONS=-Xmx2048m -Xms256m
    volumes:
      - ./logs:/logs
    restart: unless-stopped
    networks:
      - spring_network

volumes:
  mysql_data:

networks:
  spring_network:
